collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

#SEO Tags
title: Vera's Portfolio & Blog
description: A Portfolio and Blog site run by VeraDonna with blog posts mainly being about current coding projects
url: www.veradonna.co.za
author: VeraDonna
logo:
    path: /assets/imgs/favicon/android-chrome-512x512.png